default: &default
  host: localhost
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: url_shortener_api_development
  username: <%= ENV.fetch('DB_DEV_USERNAME') { 'postgres' } %>
  password: <%= ENV.fetch('DB_DEV_PASSWORD') { 'postgres' } %>

production:
  <<: *default
  database: url_shortener_api_production
  username: <%= ENV.fetch('DB_PROD_USERNAME') { nil } %>
  password: <%= ENV.fetch('DB_PROD_PASSWORD') { nil } %>

test:
  <<: *default
  database: url_shortener_api_test
  username: <%= ENV.fetch('DB_DEV_USERNAME') { 'postgres' } %>
  password: <%= ENV.fetch('DB_DEV_PASSWORD') { 'postgres' } %>
